// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//             'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDX1oWy0E--hJyoN4cx3bGzTOoyDIDyxHQ',
//     appId: '1:655114540667:android:76919d3f192c37bbfb74de',
//     messagingSenderId: '655114540667',
//     projectId: 'ealearun-kc-temp',
//     storageBucket: 'ealearun-kc-temp.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCvZqlRcbHG7aFfbRaCxBWdtywQEzXtLsI',
//     appId: '1:655114540667:ios:d48c23429a619c8dfb74de',
//     messagingSenderId: '655114540667',
//     projectId: 'ealearun-kc-temp',
//     storageBucket: 'ealearun-kc-temp.appspot.com',
//     androidClientId: '655114540667-v552krttfh3rajv80cd4qjqe2e88pavo.apps.googleusercontent.com',
//     iosClientId: '655114540667-sip1farb2jjq40bs0sicnm1lqjqn4b6v.apps.googleusercontent.com',
//     iosBundleId: 'com.order.kyochonchickentable.kcmanager.kcManager',
//   );
// }